language: objective-c
osx_image: xcode9.2
rvm:
- 2.2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- rvm install 2.2.5
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh